# Generated by Django 3.2 on 2022-03-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='uri',
            field=models.URLField(default='http://me.com'),
        ),
    ]
